# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "398db28ab6e441e3731f7b195a6472b5"
name = "Avip"
application_url = "https://shopify.dev/apps/default-app-home"
embedded = true
handle = "avip"

[build]
automatically_update_urls_on_dev = true
include_config_on_deploy = true

[webhooks]
api_version = "2026-07"

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/uninstalled"
  topics = ["app/uninstalled"]

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/scopes_update"
  topics = ["app/scopes_update"]

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_fulfillments,read_orders,write_fulfillments,write_orders"

[auth]
redirect_urls = [ "https://shopify.dev/apps/default-app-home/api/auth" ]
